is_border_leaf: true
lacp_pcs:
  - 12
  - 13
mclag_member_pcs:
  - lag: PortChannel12
  - lag: PortChannel13
sonic_bgp:
  - bestpath:
      as_path:
        multipath_relax: true
    bgp_as: '{{ bgp_asn }}'
    router_id: '{{ bgp_router_id }}'
  - bgp_as: '{{bgp_asn}}'
    vrf_name: Vrf1
  - bgp_as: '{{ bgp_asn }}'
sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 2
          redistribute:
            - protocol: connected
          safi: unicast
        - advertise_all_vni: true
          afi: l2vpn
          safi: evpn
    bgp_as: '{{bgp_asn}}'
  - address_family:
      afis:
        - afi: l2vpn
          route_advertise_list:
            - advertise_afi: ipv4
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: Vrf1
sonic_bgp_neighbors:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: Eth1/54
        peer_group: spine-leaf
      - neighbor: Eth1/53
        peer_group: spine-leaf
    peer_group:
      - '{{sonic_bgp_spineleaf_peergroup}}'
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: 10.4.4.5
        remote_as:
          peer_as: 64111
    vrf_name: Vrf1
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: 10.4.4.7
        remote_as:
          peer_as: 64111
    vrf_name: Vrf1
sonic_bgp_neighbors_af:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/54
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/53
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family:
          - activate: true
            afi: ipv4
            safi: unicast
        neighbor: 10.4.4.5
    vrf_name: Vrf1
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family:
          - activate: true
            afi: ipv4
            safi: unicast
        neighbor: 10.4.4.7
    vrf_name: Vrf1
sonic_config:
  lines: []
sonic_interfaces:
  - description: '"Uplink"'
    enabled: true
    name: Eth1/1
  - description: '"Uplink"'
    enabled: true
    name: Eth1/2
  - description: '"Node-03_eth1-PCIe-NIC1-1G-2"'
    enabled: true
    name: Eth1/5
  - description: '"Node-04_eth1-PCIe-NIC1-1G-2"'
    enabled: true
    name: Eth1/6
  - description: '"Uplink to SONICV4-SPINE-2 Eth1/2"'
    enabled: true
    name: Eth1/53
  - description: '"Uplink to SONICV4-SPINE-1 Eth1/2"'
    enabled: true
    name: Eth1/54
  - description: '"MCLAG to SONICV4-LEAF-1 Eth1/55"'
    enabled: true
    name: Eth1/55
  - description: '"MCLAG to SONICV4-LEAF-1 Eth1/56"'
    enabled: true
    name: Eth1/56
  - description: router-id
    name: '{{ loopback_inf0 }}'
  - description: vtep
    name: '{{ loopback_inf1 }}'
  - description: '"LAG to Compute_1_Node-03_bond0"'
    mtu: 9216
    name: PortChannel12
  - description: '"LAG to Compute_1_Node-04_bond0"'
    mtu: 9216
    name: PortChannel13
sonic_l2_interfaces:
  - name: Eth1/1
    trunk:
      allowed_vlans:
        - vlan: 200
  - name: Eth1/2
    trunk:
      allowed_vlans:
        - vlan: 200
  - name: PortChannel 12
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 103
  - name: PortChannel 13
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 103
  - name: PortChannel100
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 103
        - vlan: 201
        - vlan: 202
        - vlan: 203
        - vlan: 60
sonic_l3_interfaces:
  - ipv6:
      enabled: true
    name: Eth1/53
  - ipv6:
      enabled: true
    name: Eth1/54
  - ipv4:
      addresses:
        - address: '{{ loopback0_ip }}'
    name: '{{ loopback_inf0 }}'
  - ipv4:
      addresses:
        - address: '{{ loopback1_ip }}'
    name: '{{ loopback_inf1 }}'
  - ipv4:
      addresses:
        - address: 10.4.4.4/31
    name: Vlan200
sonic_lag_interfaces:
  - members:
      interfaces:
        - member: Eth1/5
    mode: lacp
    name: PortChannel12
  - members:
      interfaces:
        - member: Eth1/6
    mode: lacp
    name: PortChannel13
  - members:
      interfaces:
        - member: Eth1/55
        - member: Eth1/56
    name: PortChannel100
sonic_system:
  anycast_address:
    ipv4: true
    mac_address: '{{ anycast_mac_address }}'
  hostname: SONICV4-LEAF-2
  interface_naming: standard
sonic_vlans:
  - vlan_id: 200
  - vlan_id: 101
  - vlan_id: 102
  - vlan_id: 103
  - vlan_id: 201
  - vlan_id: 202
  - vlan_id: 203
  - vlan_id: 60
sonic_vrf_interfaces:
  - members:
      interfaces:
        - name: Vlan101
        - name: Vlan60
        - name: Vlan102
        - name: Vlan103
        - name: Vlan201
        - name: Vlan202
        - name: Vlan203
        - name: Vlan200
    name: Vrf1
sonic_vxlans:
  - evpn_nvo: nvo1
    name: vtep1
    source_ip: '{{ loopback1_ip.split(''/'')[0] }}'
    vlan_map:
      - vlan: 101
        vni: 10101
      - vlan: 201
        vni: 10201
      - vlan: 202
        vni: 10202
      - vlan: 203
        vni: 10203
      - vlan: 102
        vni: 10102
      - vlan: 103
        vni: 10103
      - vlan: 60
        vni: 600
    vrf_map:
      - vni: 600
        vrf: Vrf1
vlans:
  - 101
  - 102
  - 103
  - 201
  - 202
  - 203
vrfs:
  - Vrf1
